stages:
  prep:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/spam.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    outs:
      - models/model.pkl
      - models/vectorizer.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test.csv
      - models/model.pkl
    outs:
      - reports/metrics.txt
